const dailyTopSlides = {
  page: 50,
  results: [
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 725201,
      title: 'The Gray Man',
      original_language: 'en',
      original_title: 'The Gray Man',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 1400.175,
      release_date: '2022-07-13',
      video: false,
      vote_average: 7.044,
      vote_count: 800,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 616037,
      title: 'Thor: Love and Thunder',
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [28, 12, 14],
      popularity: 18514.843,
      release_date: '2022-07-06',
      video: false,
      vote_average: 6.707,
      vote_count: 1425,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 798223,
      title: 'Recurrence',
      original_language: 'es',
      original_title: 'Pipa',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [53, 80, 18],
      popularity: 54.886,
      release_date: '2022-07-27',
      video: false,
      vote_average: 6.278,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 507086,
      title: 'Jurassic World Dominion',
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 7695.951,
      release_date: '2022-06-01',
      video: false,
      vote_average: 7.067,
      vote_count: 2202,
    },
  ],
  total_pages: 10,
  total_results: 10,
};

export { dailyTopSlides };
