const dailyTopSlides = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 725201,
      title: 'The Gray Man',
      original_language: 'en',
      original_title: 'The Gray Man',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 1400.175,
      release_date: '2022-07-13',
      video: false,
      vote_average: 7.044,
      vote_count: 800,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 616037,
      title: 'Thor: Love and Thunder',
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [28, 12, 14],
      popularity: 18514.843,
      release_date: '2022-07-06',
      video: false,
      vote_average: 6.707,
      vote_count: 1425,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 798223,
      title: 'Recurrence',
      original_language: 'es',
      original_title: 'Pipa',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [53, 80, 18],
      popularity: 54.886,
      release_date: '2022-07-27',
      video: false,
      vote_average: 6.278,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: 'image.jpg',
      id: 507086,
      title: 'Jurassic World Dominion',
      original_language: 'en',
      original_title: 'Jurassic World Dominion',
      overview: 'description',
      poster_path: '/path',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 7695.951,
      release_date: '2022-06-01',
      video: false,
      vote_average: 7.067,
      vote_count: 2202,
    },
  ],
  total_pages: 10,
  total_results: 10000,
};

const movieDescription = {
  adult: false,
  backdrop_path: '/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg',
  belongs_to_collection: null,
  budget: 200000000,
  genres: [
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 10751,
      name: 'Family',
    },
  ],
  homepage: 'https://movies.disney.com/lightyear',
  id: 718789,
  imdb_id: 'tt10298810',
  original_language: 'en',
  original_title: 'Lightyear',
  overview: `Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits
     and his robot companion Sox.`,
  popularity: 3273.092,
  poster_path: '/ox4goZd956BxqJH6iLwhWPL9ct4.jpg',
  production_companies: [
    {
      id: 2,
      logo_path: '/wdrCwmRnLFJhEoH8GSfymY85KHT.png',
      name: 'Walt Disney Pictures',
      origin_country: 'US',
    },
    {
      id: 3,
      name: 'Pixar',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2022-06-15',
  revenue: 222400000,
  runtime: 107,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Infinity awaits.',
  title: 'Lightyear',
  video: false,
  vote_average: 7.362,
  vote_count: 1262,
};

const trailers = {
  id: 123,
  results: [
    {
      iso_639_1: 'en',
      iso_3166_1: 'US',
      name: 'Official Trailer 2',
      key: 'wHBBoUtJHhA',
      site: 'YouTube',
      size: 1080,
      type: 'Trailer',
      official: true,
      published_at: '2022-04-21T14:00:52.000Z',
      id: '62616cd2d4cc8e00a56d4a0a',
    },
    {
      iso_639_1: 'en',
      iso_3166_1: 'US',
      name: 'Official Trailer',
      key: 'BwZs3H_UN3k',
      site: 'YouTube',
      size: 1080,
      type: 'Trailer',
      official: true,
      published_at: '2022-02-08T15:00:30.000Z',
      id: '62029ad3e004a600b847dd2d',
    },
    {
      iso_639_1: 'en',
      iso_3166_1: 'US',
      name: 'Teaser Trailer',
      key: 'BwPL0Md_QFQ',
      site: 'YouTube',
      size: 1080,
      type: 'Trailer',
      official: true,
      published_at: '2021-10-27T12:46:06.000Z',
      id: '6179510af85958002a4b559b',
    },
  ],
};

const searchMock = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/xAC9kXLxUHpdCkISgYcLzYrxIQR.jpg',
      genre_ids: [53, 27],
      id: 84348,
      original_language: 'en',
      original_title: 'V/H/S',
      overview:
        'When a group of misfits is hired by an unknown third party to burglarize a desolate house and acquire one rare' +
        ' VHS tape, they discover more found footage than they had bargained for.',
      popularity: 22.647,
      poster_path: '/xVGfCaTwVdZt3lFqtOVhTDqmG58.jpg',
      release_date: '2012-07-28',
      title: 'V/H/S',
      video: false,
      vote_average: 6.1,
      vote_count: 1190,
    },
    {
      adult: false,
      backdrop_path: '/aELgHEHFGDCcGslMoyg9KGiDV4v.jpg',
      genre_ids: [27, 53],
      id: 159117,
      original_language: 'en',
      original_title: 'V/H/S/2',
      overview:
        'Inside a darkened house looms a column of TVs littered with VHS tapes, a pagan shrine to forgotten analog gods.' +
        ' The screens crackle and pop endlessly with monochrome vistas of static white noise permeating the brain and' +
        ' fogging concentration. But you must fight the urge to relax: this is no mere movie night. Those obsolete spools' +
        ' contain more than just magnetic tape. They are imprinted with the very soul of evil.',
      popularity: 27.287,
      poster_path: '/o4hcWsHaHaNQ9BBReOxLvYJNRhA.jpg',
      release_date: '2013-06-06',
      title: 'V/H/S/2',
      video: false,
      vote_average: 6.3,
      vote_count: 813,
    },
    {
      adult: false,
      backdrop_path: '/uWbP41poWgP0f7sgAQTf6UeRtwg.jpg',
      genre_ids: [27],
      id: 753453,
      original_language: 'en',
      original_title: 'V/H/S/94',
      overview:
        'A mysterious VHS tape leads a police S.W.A.T. team to the discovery of a sinister cult whose collection of' +
        ' pre-recorded material reveals a nightmarish conspiracy.',
      popularity: 23.438,
      poster_path: '/9fSogEkqDfJQTuGHsTFloQz3Tw8.jpg',
      release_date: '2021-09-26',
      title: 'V/H/S/94',
      video: false,
      vote_average: 6.3,
      vote_count: 254,
    },
    {
      adult: false,
      backdrop_path: '/td9f8E6W8Z2HnmmU69tT7ZHwK5F.jpg',
      genre_ids: [80, 53, 35, 9648],
      id: 27004,
      original_language: 'en',
      original_title: 'Ca$h',
      overview:
        'A stroke of good luck turns lethal for Sam Phelan and his wife Leslie when they are faced with a life-changing' +
        ' decision that brings strange and sinister Pyke Kubic to their doorstep. As Pyke leads Sam and Leslie on a tumultuous' +
        ' adventure through the streets of Chicago, each are pulled deeper and deeper into a desperate spiral of deception' +
        ' and violence – all in the name of money.',
      popularity: 10.3,
      poster_path: '/nEeeKsfN1hr98aCmL16LVOckawC.jpg',
      release_date: '2010-01-01',
      title: 'Ca$h',
      video: false,
      vote_average: 5.9,
      vote_count: 192,
    },
  ],
  total_pages: 25,
  total_results: 499,
};

export { dailyTopSlides, movieDescription, trailers, searchMock };
